// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')
require("chromedriver")
driver = new Builder().forBrowser('chrome').build()
/*
describe('cadastro_centrais', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('cadastro_centrais', 
  */
  async function cadastro_centrais() {
    
    // Test name: cadastro_centrais
    // Step # | name | target | value
    // 1 | open | https://10.100.20.101/admin/login_login.action | 
    await driver.get("https://10.100.20.101/admin/login_login.action")
    // 2 | setWindowSize | 1264x666 | 
    await driver.manage().window().setRect({ width: 1264, height: 666 })

    await driver.findElement(By.id('details-button')).click();
    await driver.findElement(By.id('proceed-link')).click();

    // 3 | type | id=loginName | system
    await driver.findElement(By.id("loginName")).sendKeys("system")
    // 4 | type | id=loginPass | admin123
    await driver.findElement(By.id("loginPass")).sendKeys("admin123")
    // 5 | click | id=btnLogin | 
    await driver.findElement(By.id("btnLogin")).click()
    // 6 | selectFrame | index=0 | 
    //await driver.switchTo().frame(0)
    // 7 | click | css=.menu-li-cls:nth-child(1) .h-menu-btn-cls | 
    await driver.findElement(By.css(".menu-li-cls:nth-child(1) .h-menu-btn-cls")).click()
    // 8 | selectFrame | relative=parent | 
    await driver.switchTo().defaultContent()
    // 9 | selectFrame | index=1 | 
    await driver.switchTo().frame(1)

    for(var i = 1; i < 3; i++){
      // 10 | click | id=add | 
      await driver.findElement(By.id("add")).click()
      // 11 | click | css=.inputline:nth-child(1) .label4s | 
      await driver.findElement(By.css(".inputline:nth-child(1) .label4s")).click()
      // 12 | click | css=.selectlist > li:nth-child(3) > span | 
      await driver.findElement(By.css(".selectlist > li:nth-child(3) > span")).click()
      // 13 | click | id=macAddress | 
      await driver.findElement(By.id("macAddress")).click()
      // 14 | type | id=macAddress | 123456789
      await driver.findElement(By.id("macAddress")).sendKeys(123456789 + i)
      // 15 | click | id=adbc1 | 
      await driver.findElement(By.id("adbc1")).click()
      // 16 | click | id=name | 
      await driver.findElement(By.id("name")).click()
      // 17 | type | id=name | central 1
      await driver.findElement(By.id("name")).sendKeys("central " + i)
      // 18 | click | id=adbc4 | 
      await driver.findElement(By.id("adbc4")).click()
    }
    
  //})
//})
  }

  cadastro_centrais()
